/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author danie
 */
import java.awt.*;
import javax.swing.*;
import controller.GameController;
import controller.KeyHandler;

public class GamePanel extends JPanel {
    private GameController ctrl;
    private BoardPanel boardPanel;
    private JLabel scoreLabel;
    private JLabel levelLabel;

    public GamePanel() {
        setLayout(new BorderLayout());
        setBackground(Color.BLACK);
        ctrl       = new GameController(this);
        boardPanel = new BoardPanel(ctrl);

        // Panel lateral derecho con el puntaje
        JPanel side = new JPanel(new GridLayout(4, 1, 0, 10));
        side.setBackground(Color.BLACK);
        side.setBorder(BorderFactory.createEmptyBorder(20, 12, 20, 12));

        JLabel title = new JLabel("SNAKE", SwingConstants.CENTER);
        title.setForeground(Color.GREEN);
        title.setFont(new Font("Arial", Font.BOLD, 20));

        scoreLabel = new JLabel("<html><center>PUNTAJE<br>0</center></html>", SwingConstants.CENTER);
        scoreLabel.setForeground(Color.WHITE);
        scoreLabel.setFont(new Font("Arial", Font.BOLD, 14));
        scoreLabel.setOpaque(true);
        scoreLabel.setBackground(Color.BLACK);
        scoreLabel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        
        levelLabel = new JLabel("<html><center>NIVEL<br>1</center></html>", SwingConstants.CENTER);
        levelLabel.setForeground(Color.WHITE);
        levelLabel.setFont(new Font("Arial", Font.BOLD,14));
        levelLabel.setOpaque(true);
        levelLabel.setBackground(Color.BLACK);
        levelLabel.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        JLabel hint = new JLabel("<html><center>P = Pausa<br>Flechas = mover</center>R = Resetear</html>", SwingConstants.CENTER);
        hint.setForeground(Color.GRAY);
        hint.setFont(new Font("Arial", Font.PLAIN, 11));

        side.add(title);
        side.add(scoreLabel);
        side.add(levelLabel);
        side.add(hint);

        add(boardPanel, BorderLayout.CENTER);
        add(side, BorderLayout.EAST);

        addKeyListener(new KeyHandler(ctrl));
        setFocusable(true);
    }

     @Override
    public void repaint() {
        super.repaint();
        // Actualiza el puntaje en el panel lateral
        if (scoreLabel != null && ctrl != null){
            scoreLabel.setText("<html><center>PUNTAJE<br>"
                + ctrl.getState().getScore() + "</center></html>");
        }
        // Actualiza el nivel en el panel lateral
        if (levelLabel != null && ctrl != null) {
        levelLabel.setText("<html><center>NIVEL<br>"
            + ctrl.getState().getLabel() + "</center></html>");
    }
        if (boardPanel != null) boardPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
